- package.json
- Added 2 new endpoints and added some additional fields in other places
> Release 0.0.4-canary.8

- packages/api/graphql/fragments/base-ledger-account-fragment.graphql
- packages/api/graphql/mutations/transfer-funds.graphql
- packages/api/graphql/queries/company-ledger-account.graphql
- packages/api/graphql/queries/user-ledger-account.graphql
- packages/api/package.json
- packages/api/src/index.ts
- packages/api/src/webhook-types.ts
- packages/api/src/webhooks.ts
feat: transfer funds and ai webhook types
> feat: transfer funds and ai webhook types

- packages/api/package.json
- packages/api/src/index.ts
- packages/api/src/verifyUserToken.ts
- packages/api/src/webhook-types.ts
- pnpm-lock.yaml
feat: add verify token to the api package
> feat: add verify token to the api package

- packages/api/graphql/fragments/base-plan-fragment.graphql
- packages/api/graphql/fragments/experience-fragment.graphql
- packages/api/graphql/mutations/charge-user.graphql
- packages/api/graphql/queries/company-ledger-account.graphql
- packages/api/graphql/queries/list-experiences.graphql
- packages/api/package.json
- packages/api/src/index.ts
- packages/api/src/verifyUserToken.ts
- packages/api/src/webhook-types.ts
- packages/api/src/webhooks.ts
feat: add list experiences endpoint
> feat: add list experiences endpoint

- README.md
- packages/api/graphql/fragments/access-pass-fragment.graphql
- packages/api/graphql/queries/access-pass.graphql
- packages/api/graphql/queries/has-access.graphql
- packages/api/graphql/queries/public-user.graphql
- packages/api/package.json
> feat: has access endpoints

- packages/api/graphql/fragments/forum-post-fragment.graphql
- packages/api/graphql/mutations/create-forum-post.graphql
- packages/api/graphql/mutations/send-notification.graphql
- packages/api/package.json
feat: notifications and creating forum posts
> feat: notifications and creating forum posts

- packages/api/graphql/fragments/experience-fragment.graphql
- packages/api/graphql/queries/experience.graphql
- packages/api/package.json
fix: list experiences image style
> fix: list experiences image style

- packages/api/graphql/mutations/Engagement/create-chat.graphql
- packages/api/graphql/mutations/Engagement/create-forum.graphql
- packages/api/package.json
Fixed names and regenned the build dist to work for new be types!
> updated names

- packages/api/package.json
- pnpm-lock.yaml
Bump `tsup` package to resolve dependabot alert
> chore(deps): bump `tsup` to 8.5.0

- apps/docs/.gitignore
- examples/next.js/components/examples/section-08-connect-to-the-websocket/index.client.tsx
- examples/next.js/components/examples/section-08-connect-to-the-websocket/index.tsx
- packages/api/package.json
- packages/api/src/index.shared.ts
- packages/api/src/websockets/client.common.ts
feat: add client side broadcast to examples project
> feat: add client side broadcast to examples project

- apps/docs/features/websocket-guide.mdx
- examples/next.js/components/examples/section-08-connect-to-the-websocket/index.client.tsx
- packages/api/package.json
- packages/api/src/sdk/client-sdk-shared.ts
- packages/api/src/sdk/server-sdk-shared.ts
- packages/api/src/websockets/client.browser.ts
- packages/api/src/websockets/client.common.ts
- packages/api/src/websockets/client.server.ts
- pnpm-lock.yaml
feat: websocket docs and websocket api update
> feat: websocket docs and websocket api update

- .vscode/settings.json
- apps/docs/features/oauth-guide.mdx
- apps/docs/features/post-to-feed.mdx
- apps/docs/features/upload-media.mdx
- apps/docs/features/websocket-guide.mdx
- apps/docs/introduction.mdx
- apps/docs/mint.json
- examples/nextjs/README.md
> feat: post to feed docs

- apps/docs/tutorials/ai-image-generator.mdx
> Tweak tutorial doc

- apps/docs/tutorials/ai-image-generator.mdx
- examples/ai-image-generator/app/api/experiences/[experienceId]/generate/route.ts
use companyId instead of bizId
update docs to reflect code
> Modify tutorial to have consistent naming

- apps/docs/sdk/api/chats/send-message-to-chat.mdx
- apps/docs/sdk/api/direct-messages/send-direct-message-to-user.mdx
- examples/penny-bidding/app/api/cron/route.ts
- examples/penny-bidding/app/api/webhooks/route.ts
- examples/penny-bidding/app/experiences/[experienceId]/layout.tsx
- examples/penny-bidding/components/credit-balance/index.tsx
- examples/penny-bidding/components/experience-overlay.tsx
- examples/penny-bidding/lib/actions/create-listing.ts
- examples/penny-bidding/lib/actions/mark-as-fulfilled.ts
- examples/penny-bidding/lib/actions/place-bid.ts
- examples/penny-bidding/lib/actions/relist.ts
- examples/penny-bidding/lib/actions/request-topup.ts
- examples/penny-bidding/lib/db/schema/index.ts
- examples/penny-bidding/vercel.json
- packages/api/graphql/operations/chats/send-message-to-chat.graphql
- packages/api/graphql/operations/direct-messages/send-direct-message-to-user.graphql
feat: add notificaitons to penny bidding app
> feat: add notificaitons to penny bidding app

- apps/docs/features/payments-and-payouts.mdx
- apps/docs/sdk/api/direct-messages/list-direct-message-conversations.mdx
Updates the documentation in `payments-and-payouts` to reflect recent changes to the underlying APIs and align better with recommended best practices.
> chore: update docs for in app payments

- apps/docs/sdk/api/access-passes/get-access-pass.mdx
- apps/docs/sdk/api/attachments/get-attachment.mdx
- apps/docs/sdk/api/attachments/process-attachment.mdx
- apps/docs/sdk/api/attachments/upload-media.mdx
- apps/docs/sdk/api/authentication/check-if-user-has-access-to-access-pass.mdx
- apps/docs/sdk/api/authentication/check-if-user-has-access-to-company.mdx
- apps/docs/sdk/api/authentication/check-if-user-has-access-to-experience.mdx
- apps/docs/sdk/api/authentication/get-current-user.mdx
- apps/docs/sdk/api/authentication/list-experiences.mdx
- apps/docs/sdk/api/chats/find-or-create-chat.mdx
- apps/docs/sdk/api/chats/list-messages-from-chat.mdx
- apps/docs/sdk/api/chats/send-message-to-chat.mdx
- apps/docs/sdk/api/companies/get-waitlist-entries-for-company.mdx
- apps/docs/sdk/api/direct-messages/list-direct-message-conversations.mdx
- apps/docs/sdk/api/direct-messages/send-direct-message-to-user.mdx
- apps/docs/sdk/api/experiences/get-experience.mdx
- apps/docs/sdk/api/experiences/list-users-for-experience.mdx
- apps/docs/sdk/api/forums/create-forum-post.mdx
- apps/docs/sdk/api/forums/find-or-create-forum.mdx
- apps/docs/sdk/api/forums/list-forum-posts-from-forum.mdx
- apps/docs/sdk/api/notifications/send-push-notification.mdx
- apps/docs/sdk/api/payments/charge-user.mdx
- apps/docs/sdk/api/payments/get-company-ledger-account.mdx
- apps/docs/sdk/api/payments/get-user-ledger-account.mdx
- apps/docs/sdk/api/payments/pay-user.mdx
- apps/docs/sdk/api/users/get-user.mdx
- packages/graphql-codegen-docs/src/index.ts
- packages/graphql-codegen-docs/src/input.ts
> feat: example outputs

- apps/docs/features/checkout-embed.mdx
- packages/checkout/.npmignore
- packages/checkout/README.md
- packages/checkout/package.json
- packages/checkout/public/index.html
- packages/checkout/public/success.html
The platform side of this integration just landed so we are bumping the stage to public beta and are updating the docs accordingly
> feat: stabilize embedded checkout

- .changeset/beige-flies-begin.md
- .changeset/loud-peas-shout.md
- .changeset/pre.json
- .github/workflows/release.yml
- apps/docs/features/checkout-embed.mdx
- packages/checkout/README.md
- packages/checkout/package.json
- packages/checkout/src/index.ts
- packages/checkout/src/util.ts
- packages/checkout/tsup.config.ts
- packages/checkout/turbo.json
- packages/react/README.md
- packages/react/package.json
- packages/react/src/checkout.ts
- packages/react/src/checkout/embed.tsx
- packages/react/src/checkout/util.ts
- packages/react/src/util/use-is-hydrated.ts
- pnpm-lock.yaml
This PR add the `WhopCheckoutEmbed` component to the `@whop/react` package. it also adds a util file in the checkout package that is heavily used by itself and the react package.
> feat(react): add `WhopCheckoutEmbed` component

- examples/nextjs/components/examples/section-02-get-user-details/index.client.tsx
- examples/nextjs/components/examples/section-02-get-user-details/index.tsx
feat: add example of how to open whop profile modal
> feat: add example of how to open whop profile modal

- examples/penny-bidding/app/api/cron/route.ts
- examples/penny-bidding/app/api/webhooks/route.ts
fix: some errors in example app
> fix: some errors in example app

- apps/docs/sdk/external-url.mdx
docs: how to display a user profile modal
> docs: how to display a user profile modal

- .changeset/nice-teams-beg.md
- packages/react/package.json
- packages/react/src/checkout.ts
- packages/react/src/checkout/index.ts
- packages/react/src/components/index.ts
- packages/react/src/components/whop-app.tsx
- packages/react/src/index.ts
This PR improves sub-package discoverability in code editors by explicitly defining entry points in the `exports` field of `package.json`.
- **Explicit Exports:**  
The `exports` field in `package.json` has been updated to provide clear entry points for sub-packages, enhancing code editor support and autocompletion.
- **Refactored Structure:**  
The `src` directory has been reorganized by moving files such as `components.ts` to `components/index.ts`, resulting in a cleaner and more maintainable folder structure.
> feat(react): update `exports` in package.json

- apps/docs/features/subscriptions.mdx
- apps/docs/mint.json
> feat: subscriptions docs

- .changeset/gold-friends-make.md
- packages/api/codegen.ts
- packages/api/src/sdk/client-sdk-shared.ts
- packages/api/src/sdk/sdk-common.ts
- packages/api/src/sdk/server-sdk-shared.ts
feat: add operation name to url
> feat: add operation name to url

- .changeset/afraid-loops-count.md
- apps/docs/features/subscriptions.mdx
- apps/docs/mint.json
- apps/docs/sdk/api/payments/create-checkout-session.mdx
- packages/api/graphql/operations/payments/create-checkout-session.server.graphql
feat: add create checkout session function to the SDK
> feat: add create checkout session function to the SDK

- apps/docs/features/send-push-notification.mdx
- apps/docs/sdk/api/access-passes/get-access-pass.mdx
- apps/docs/sdk/api/access/check-if-user-has-access-to-access-pass.mdx
- apps/docs/sdk/api/access/check-if-user-has-access-to-company.mdx
- apps/docs/sdk/api/access/check-if-user-has-access-to-experience.mdx
- apps/docs/sdk/api/apps/create-app-build.mdx
- apps/docs/sdk/api/attachments/get-attachment.mdx
- apps/docs/sdk/api/attachments/process-attachment.mdx
- apps/docs/sdk/api/attachments/upload-media.mdx
- apps/docs/sdk/api/companies/get-company-ledger-account.mdx
- apps/docs/sdk/api/companies/get-waitlist-entries-for-company.mdx
- apps/docs/sdk/api/experiences/get-experience.mdx
- apps/docs/sdk/api/experiences/list-experiences.mdx
- apps/docs/sdk/api/experiences/list-users-for-experience.mdx
- apps/docs/sdk/api/forums/create-forum-post.mdx
- apps/docs/sdk/api/forums/find-or-create-forum.mdx
- apps/docs/sdk/api/forums/list-forum-posts-from-forum.mdx
- apps/docs/sdk/api/messages/find-or-create-chat.mdx
- apps/docs/sdk/api/messages/list-direct-message-conversations.mdx
- apps/docs/sdk/api/messages/list-messages-from-chat.mdx
- apps/docs/sdk/api/messages/send-direct-message-to-user.mdx
- apps/docs/sdk/api/messages/send-message-to-chat.mdx
- apps/docs/sdk/api/notifications/send-push-notification.mdx
- apps/docs/sdk/api/payments/charge-user.mdx
- apps/docs/sdk/api/payments/create-checkout-session.mdx
- apps/docs/sdk/api/payments/pay-user.mdx
- apps/docs/sdk/api/users/get-current-user.mdx
- apps/docs/sdk/api/users/get-user-ledger-account.mdx
- apps/docs/sdk/api/users/get-user.mdx
- packages/graphql-codegen-docs/src/index.ts
feat: improve notifications docs
> feat: improve notifications docs

- .changeset/rare-pans-invent.md
- packages/react/src/checkout/framer.tsx
Adds the `fallback` prop to the framer property controls for completeness
> feat: add fallback prop to framer checkout embed

- .changeset/strong-beds-check.md
- packages/react/package.json
Framer can not resolve the /checkout/framer sub package so im trying to fix it by reordering the exports in the package.json
> fix(react): recorder package.json exports

- .changeset/nine-humans-wink.md
- apps/docs/mint.json
- apps/docs/sdk/api/experiences/list-access-passes-for-experience.mdx
- examples/nextjs/components/examples/section-02-get-user-details/index.tsx
- examples/nextjs/components/examples/section-03-get-experience-details/index.tsx
- packages/api/graphql/operations/experiences/list-access-passes-for-experience.server.graphql
feat: add list access passes for experience query
> feat: add list access passes for experience query

- .changeset/hot-bugs-sit.md
- apps/docs/sdk/api/access-passes/get-access-pass.mdx
- packages/api/graphql/operations/access-passes/get-access-pass.shared.graphql
feat: add attachments to access pass
> feat: add attachments to access pass

- apps/docs/building-apps.mdx
Add note on:
- properly linking to whops (include discover in path which helps our tracking)
- how to use affiliate query params
> add note on linking to whops and affiliates

- .changeset/fine-grapes-joke.md
- packages/api/src/oauth/index.ts
> fix: state missing in oauth url

- .changeset/silent-spiders-add.md
- packages/react-native/src/lib/client-sdk.ts
- packages/react-native/src/lib/index.ts
- packages/react-native/src/lib/native-whop-core-wrapper.ts
feat: Allow interacting with the internal native whop core api
> feat: Allow interacting with the internal native whop core api

- .changeset/moody-jeans-clap.md
- packages/react-native/src/lib/native-whop-core-wrapper.ts
- packages/react-native/src/lib/props.ts
feat: native router for react native
> feat: native router for react native

- .changeset/itchy-mirrors-change.md
- packages/react-native/src/lib/native-whop-core-wrapper.ts
- packages/react-native/src/lib/props.ts
feat: add ability to present sheets and set navigation bar data
> feat: add ability to present sheets and set navigation bar data

- .changeset/wicked-teams-serve.md
- apps/docs/sdk/api/attachments/upload-media.mdx
- apps/docs/sdk/api/courses/update-lesson.mdx
- packages/create-react-native/template/src/views/discover-view.tsx
- packages/create-react-native/template/src/views/experience-view.tsx
- packages/create-react-native/template/tsconfig.json
- packages/react-native/src/lib/native-whop-core-wrapper.ts
add in app purchase async call
> add in app purchase async call

- .changeset/thirty-peas-dream.md
- apps/docs/features/oauth-guide.mdx
- packages/api/package.json
- packages/api/src/oauth/index.ts
- pnpm-lock.yaml
This will make it easier to implement Whop OAuth with auth.js frameworks
> feat: add auth.js oauth provider + docs

- .changeset/thick-sloths-join.md
> add changeset

- .changeset/hip-hands-lie.md
- apps/docs/mint.json
- apps/docs/tutorials/react-native.mdx
- packages/react-native/package.json
- packages/react-native/src/cli/index.ts
- packages/react-native/src/cli/sdk.ts
- pnpm-lock.yaml
> feat: react native docs

- .changeset/poor-points-admire.md
- apps/docs/features/checkout-embed.mdx
- packages/checkout/README.md
- packages/checkout/src/errors.ts
- packages/checkout/src/index.ts
- packages/checkout/src/loader.ts
- packages/checkout/src/messages.ts
- packages/checkout/src/rpc.ts
- packages/checkout/src/types.d.ts
- packages/checkout/src/util.ts
- packages/checkout/src/uuid-v4.ts
- packages/react/README.md
- packages/react/src/checkout/embed.tsx
- packages/react/src/checkout/util.ts
Implements the `getEmail` event on the embedded checkout frame
> feat(checkout): implement getEmail

- .changeset/shaky-tools-sit.md
- apps/docs/sdk/api/apps/create-app-build.mdx
- packages/react-native/package.json
- packages/react-native/src/cli/index.ts
- packages/react-native/src/cli/mobile.ts
- packages/react-native/src/cli/reanimated-bable.ts
- packages/react-native/src/cli/strip-flow.ts
- packages/react-native/src/cli/valid-view-type.ts
- packages/react-native/src/cli/web.ts
- packages/react-native/src/lib/haptics.ts
- packages/react-native/src/lib/index.ts
- packages/react-native/src/lib/native-whop-core-stub.ts
- packages/react-native/src/lib/native-whop-core.ts
- packages/react-native/src/lib/web-router.ts
- packages/react-native/src/lib/web.ts
- packages/react-native/tsup.config.ts
- pnpm-lock.yaml
feat: add web support to react native
> feat: add web support to react native

- apps/docs/apps/tutorials/dashboard-apps.mdx
- apps/docs/package.json
- pnpm-lock.yaml
update mintify and add dashboard apps docs
> update mintify and add dashboard apps docs

- .changeset/swift-planets-wave.md
- apps/docs/sdk/api/companies/get-company.mdx
- packages/api/graphql/operations/companies/get-company.shared.graphql
- typos.toml
> sdk: add business/industry type to getCompany

- apps/docs/apps/features/oauth-guide.mdx
- examples/oauth-nextjs/.env.example
- examples/oauth-nextjs/.gitignore
- examples/oauth-nextjs/README.md
- examples/oauth-nextjs/app/api/auth/[...nextauth]/route.ts
- examples/oauth-nextjs/app/buttons.tsx
- examples/oauth-nextjs/app/globals.css
- examples/oauth-nextjs/app/layout.tsx
- examples/oauth-nextjs/app/page.tsx
- examples/oauth-nextjs/auth.ts
- examples/oauth-nextjs/eslint.config.mjs
- examples/oauth-nextjs/next.config.ts
- examples/oauth-nextjs/package.json
- examples/oauth-nextjs/postcss.config.mjs
- examples/oauth-nextjs/tsconfig.json
- examples/oauth-nextjs/turbo.json
- examples/oauth-nextjs/types/next-auth.d.ts
- examples/oauth-nextjs/whop.ts
- pnpm-lock.yaml
I made this example a while ago to validate the auth.js setup with our provider. It should serve as a good point of reference for developers wanting to use oauth.
> docs: add example for oauth with nextjs + authjs

- apps/docs/payments/set-up-payouts.mdx
added canceled as status for payouts doc
> update payouts doc

- apps/docs/payments/create-checkout-link.mdx
> update create checkout link doc

- apps/docs/set-up-store-page.mdx
changed from store page to product page, cleaned up any inconsistencies
> setup product page

- apps/docs/payments/resolution-center.mdx
updated res center docs with bnpl policy
> update res center docs

- apps/docs/payments/create-checkout-link.mdx
- added split pay link instructions
> update create checkout links

- apps/docs/payments/set-up-payouts.mdx
> update setup payouts

- apps/docs/payments/send-an-invoice.mdx
> update invoice doc

- apps/docs/whop-apps/apps-for-businesses.mdx
> updated apps for biz docs

- apps/docs/supported-business-models/paid-groups.mdx
> update paid groups doc

- apps/docs/set-up-store-page.mdx
> fixed product page setup

- apps/docs/manage-your-business/team-management/manage-team-roles.mdx
added new sales manager perms (seeing payments table)
> updated manage team roles

- .github/workflows/auto-update-docs.yml
- apps/docs/docs.json
> update gh action
